### ISSUE TITLE
RSS source support

### ISSUE THREAD

**Issue by csharpfritz** [csharpfritz/Fritz.ConfigurationBuilders#5]
Support downloading configuration from an RSS endpoint

Let's start with no authentication support

**Comment by GiancarloLelli** [comment]
Hey @csharpfritz can I help you on this? ☺

**Comment by csharpfritz** [comment]
Absolutely...  what do you have in mind?  Comment here about your ideas,
fork, and write some code



Jeff

**Comment by GiancarloLelli** [comment]
I was thinking about creating a new class called **RssConfigurationBuilder** that just like the **IniConfigurationBuilder** inherits from **KeyValueConfigBuilder** - then, instead of parsing an ini file, it fetches from the RSS feed (which was validated in advance)  all the settings which I supposed should be in the form of _Key=Value_ pairs - Sounds good?

**Comment by csharpfritz** [comment]
Sounds like a good start.. I look forward to your contribution. 



Jeff

**Comment by GiancarloLelli** [comment]
Here's the first implementation https://github.com/GiancarloLelli/Fritz.ConfigurationBuilders/commit/62461e60a7fe8d4bbb5866e7d1cb5f086e35e02e - UniTest still missing though, any suggestions?

**Comment by csharpfritz** [comment]
Looks like a great start - I'll review further tomorrow on stream.

Thanks for the contribution!



Jeff

**Comment by GiancarloLelli** [comment]
There you go: https://github.com/csharpfritz/Fritz.ConfigurationBuilders/pull/6 :)
